CREATE TABLE IF NOT EXISTS "invoice_lines" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"invoice_id" uuid,
	"order_line_id" uuid,
	"line_number" integer NOT NULL,
	"product_id" uuid,
	"product_sku" varchar(100),
	"description" text NOT NULL,
	"quantity" numeric(10, 2) NOT NULL,
	"unit_of_measure" varchar(50),
	"unit_price" numeric(10, 2) NOT NULL,
	"discount_amount" numeric(10, 2) DEFAULT '0',
	"tax_rate" numeric(5, 2) DEFAULT '0',
	"tax_amount" numeric(10, 2) DEFAULT '0',
	"line_total" numeric(12, 2) NOT NULL,
	"qbo_line_id" varchar(50),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "invoices" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid,
	"invoice_number" varchar(255) NOT NULL,
	"invoice_type" varchar(50) DEFAULT 'standard',
	"invoice_status" varchar(50) DEFAULT 'draft',
	"order_id" uuid,
	"customer_id" uuid,
	"billing_address_id" uuid,
	"invoice_date" date DEFAULT now() NOT NULL,
	"due_date" date NOT NULL,
	"service_period_start" date,
	"service_period_end" date,
	"agent_user_id" varchar(255),
	"agent_name" varchar(255),
	"broker_user_id" varchar(255),
	"broker_name" varchar(255),
	"currency" varchar(10) DEFAULT 'USD',
	"exchange_rate" numeric(10, 4) DEFAULT '1',
	"subtotal" numeric(12, 2) DEFAULT '0',
	"discount_amount" numeric(12, 2) DEFAULT '0',
	"tax_amount" numeric(12, 2) DEFAULT '0',
	"shipping_cost" numeric(12, 2) DEFAULT '0',
	"total_amount" numeric(12, 2) NOT NULL,
	"amount_paid" numeric(12, 2) DEFAULT '0',
	"balance_due" numeric(12, 2),
	"payment_terms" varchar(100),
	"payment_method" varchar(50),
	"po_number" varchar(100),
	"notes" text,
	"terms_and_conditions" text,
	"email_sent" boolean DEFAULT false,
	"email_sent_at" timestamp,
	"email_viewed" boolean DEFAULT false,
	"email_viewed_at" timestamp,
	"qbo_invoice_id" varchar(50),
	"qbo_doc_number" varchar(50),
	"qbo_sync_token" varchar(50),
	"qbo_last_synced_at" timestamp,
	"pdf_url" text,
	"pdf_generated_at" timestamp,
	"created_by" varchar(255),
	"approved_by" varchar(255),
	"approved_at" timestamp,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "invoices_invoice_number_unique" UNIQUE("invoice_number")
);
